development:
  consumer_key: <%= ENV['EVERNOTE_CONSUMER_KEY'] %>
  consumer_secret: <%= ENV['EVERNOTE_CONSUMER_SECRET'] %>
  sandbox: true
production:
  consumer_key: <%= ENV['EVERNOTE_CONSUMER_KEY'] %>
  consumer_secret: <%= ENV['EVERNOTE_CONSUMER_SECRET'] %>
  sandbox: true
test:
  consumer_key: <%= ENV['EVERNOTE_CONSUMER_KEY'] %>
  consumer_secret: <%= ENV['EVERNOTE_CONSUMER_SECRET'] %>
  sandbox: true